import { IFood } from "./types";

export const menu: IFood[] = [
  {
    name: "Dough",
    category: "Alkohofrei",
    code: "ALKFREI001",
    description: "hausgemachtes jogurtgetränk mit Minze (G)",
    images: [
      "Toranj-48-Drinks-Dough.jpg",
      "Toranj-20-Food with Ingredients -Dough.jpg",
    ],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.5,
      },
      {
        size: "0,501",
        price: 4.9,
      },
    ],
    similar: [],
  },
  {
    name: "Granatapfelsaft",
    category: "Alkohofrei",
    code: "ALKFREI002",
    description: "gerne auch gespritzt",
    images: ["Toranj-25-One Dish-Granatapfelsaft.jpg"],
    material: "",
    price: [
      {
        size: "0,331",
        price: 4.6,
      },
      {
        size: "0,501",
        price: 5.9,
      },
    ],
    similar: [],
  },
  {
    name: "Shartbate Sekanjebin",
    category: "Alkohofrei",
    code: "ALKFREI003",
    description: "Persische Minz-Essig-Limonade mit geriebenen Gurken",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.7,
      },
      {
        size: "0,51",
        price: 4.5,
      },
    ],
    similar: [],
  },
  {
    name: "Sharbet Safran Chia",
    category: "Alkohofrei",
    code: "ALKFREI004",
    description: "Hausgemachtes Safran-Getränk mit Chia-Samen",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.9,
      },
      {
        size: "0,51",
        price: 4.6,
      },
    ],
    similar: [],
  },
  {
    name: "Sodacitron",
    category: "Alkohofrei",
    code: "ALKFREI005",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.8,
      },
      {
        size: "0,51",
        price: 4.5,
      },
    ],
    similar: [],
  },
  {
    name: "Soda Zitrone / Himbeer / Holunder**",
    category: "Alkohofrei",
    code: "ALKFREI006",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.5,
      },
      {
        size: "0,51",
        price: 4.3,
      },
    ],
    similar: [],
  },
  {
    name: "Coca Cola / Coca Cola Zero",
    category: "Alkohofrei",
    code: "ALKFREI007",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.4,
      },
    ],
    similar: [],
  },
  {
    name: "Fanta",
    category: "Alkohofrei",
    code: "ALKFREI008",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.8,
      },
    ],
    similar: [],
  },
  {
    name: "Sprite",
    category: "Alkohofrei",
    code: "ALKFREI009",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.8,
      },
    ],
    similar: [],
  },
  {
    name: "Pepsi",
    category: "Alkohofrei",
    code: "ALKFREI010",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,251",
        price: 3.1,
      },
    ],
    similar: [],
  },
  {
    name: "Almdudler",
    category: "Alkohofrei",
    code: "ALKFREI011",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.8,
      },
    ],
    similar: [],
  },
  {
    name: "Eistee Pfirsich / Zitrone",
    category: "Alkohofrei",
    code: "ALKFREI012",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.8,
      },
    ],
    similar: [],
  },
  {
    name: "Apfelsaft / Orangensaft",
    category: "Alkohofrei",
    code: "ALKFREI013",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.5,
      },
      {
        size: "0,51",
        price: 4.8,
      },
    ],
    similar: [],
  },
  {
    name: "MineralWasser - Ohne oder Prickelnd",
    category: "Alkohofrei",
    code: "ALKFREI014",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0,331",
        price: 3.2,
      },
      {
        size: "0,751",
        price: 6.5,
      },
    ],
    similar: [],
  },
  {
    name: "Ananas Minz Spritzer",
    category: "Spritzer",
    code: "SPRITZ001",
    description: "",
    images: ["Toranj-13-Drinks-Ananas Minz Spritzer.jpg"],
    material: "",
    price: [
      {
        size: "1/41",
        price: 5.3,
      },
    ],
    similar: [
      "Cranbaerry Rosemarin Spritzer",
      "Basilikum Spritzer",
      "Aperol Spritzer",
    ],
  },
  {
    name: "Cranbaerry Rosemarin Spritzer",
    category: "Spritzer",
    code: "SPRITZ002",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "1/41",
        price: 5.3,
      },
    ],
    similar: ["Ananas Minz Spritzer", "Basilikum Spritzer", "Hugo"],
  },
  {
    name: "Basilikum Spritzer",
    category: "Spritzer",
    code: "SPRITZ003",
    description: "",
    images: ["Toranj-9-Drinks-Basilikum Spritzer.jpg"],
    material: "",
    price: [
      {
        size: "1/41",
        price: 5.3,
      },
    ],
    similar: [
      "Ananas Minz Spritzer",
      "Cranbaerry Rosemarin Spritzer",
      "Aperol Spritzer",
    ],
  },
  {
    name: "Weißer Spritzer",
    category: "Spritzer",
    code: "SPRITZ004",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "1/41",
        price: 4.9,
      },
    ],
    similar: ["Hugo", "Basilikum Spritzer", "Cranbaerry Rosemarin Spritzer"],
  },
  {
    name: "Aperol Spritzer",
    category: "Spritzer",
    code: "SPRITZ005",
    description: "",
    images: ["Toranj-10-Drinks-Aperol.jpg"],
    material: "",
    price: [
      {
        size: "1/41",
        price: 5.3,
      },
    ],
    similar: ["Weißer Spritzer", "Hugo", "Ananas Minz Spritzer"],
  },
  {
    name: "Hugo",
    category: "Spritzer",
    code: "SPRITZ006",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "1/41",
        price: 5.1,
      },
    ],
    similar: ["Ananas Minz Spritzer", "Basilikum Spritzer", "Weißer Spritzer"],
  },
  {
    name: "Corona",
    category: "Bier",
    code: "BIER001",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0.331",
        price: 3.8,
      },
    ],
    similar: [
      "Gösser Märzen",
      "OTTAKRINGER Helles",
      "OTTAKRINGER Null Komma Josef (Alkoholfrei)",
    ],
  },
  {
    name: "Gösser Märzen",
    category: "Bier",
    code: "BIER002",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0.331",
        price: 3.7,
      },
      {
        size: "0.51",
        price: 4.8,
      },
    ],
    similar: ["Corona", "OTTAKRINGER Helles", "OTTAKRINGER Citrus Radler"],
  },
  {
    name: "OTTAKRINGER Helles",
    category: "Bier",
    code: "BIER003",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0.331",
        price: 3.7,
      },
      {
        size: "0.51",
        price: 4.8,
      },
    ],
    similar: [
      "Corona",
      "Gösser Märzen",
      "OTTAKRINGER Null Komma Josef (Alkoholfrei)",
    ],
  },
  {
    name: "OTTAKRINGER Citrus Radler",
    category: "Bier",
    code: "BIER004",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0.331",
        price: 3.7,
      },
      {
        size: "0.51",
        price: 4.8,
      },
    ],
    similar: [
      "Gösser Märzen",
      "OTTAKRINGER Helles",
      "OTTAKRINGER Null Komma Josef (Alkoholfrei)",
    ],
  },
  {
    name: "OTTAKRINGER Null Komma Josef (Alkoholfrei)",
    category: "Bier",
    code: "BIER005",
    description: "",
    images: [],
    material: "",
    price: [
      {
        size: "0.331",
        price: 3.7,
      },
      {
        size: "0.51",
        price: 4.8,
      },
    ],
    similar: ["Gösser Märzen", "OTTAKRINGER Helles", "Corona"],
  },
  {
    name: "Safrantee",
    category: "Tee - Kaffee",
    code: "TEE001",
    description: "Tee",
    images: ["Toranj-55-Drinks-Tee.jpg"],
    material: "",
    price: 5.6,
    similar: [
      "Teekanne / Schwarztee",
      "Kamillentee / Pfefferminztee",
      "Kandiszucker am Stiel",
    ],
  },
  {
    name: "Teekanne / Schwarztee",
    category: "Tee - Kaffee",
    code: "TEE002",
    description: "Tee",
    images: ["Toranj-56-Drinks-Tee.jpg"],
    material: "",
    price: 5.5,
    similar: [
      "Safrantee",
      "Kamillentee / Pfefferminztee",
      "Kandiszucker am Stiel",
    ],
  },
  {
    name: "Kamillentee / Pfefferminztee",
    category: "Tee - Kaffee",
    code: "TEE003",
    description: "Tee",
    images: [],
    material: "",
    price: 3.9,
    similar: ["Safrantee", "Teekanne / Schwarztee", "Kandiszucker am Stiel"],
  },
  {
    name: "Kandiszucker am Stiel",
    category: "Tee - Kaffee",
    code: "TEE004",
    description: "Tee",
    images: [],
    material: "",
    price: 1.5,
    similar: [
      "Safrantee",
      "Teekanne / Schwarztee",
      "Kamillentee / Pfefferminztee",
    ],
  },
  {
    name: "Datteln 5 Stk.",
    category: "Tee - Kaffee",
    code: "TEE005",
    description: "Tee",
    images: [],
    material: "",
    price: 2.5,
    similar: [
      "Safrantee",
      "Teekanne / Schwarztee",
      "Kamillentee / Pfefferminztee",
    ],
  },
  {
    name: "Espresso",
    category: "Tee - Kaffee",
    code: "TEE006",
    description: "Kaffee",
    images: [],
    material: "",
    price: 2.9,
    similar: ["Espresso doppio", "Kleiner Brauner (G)", "Melange (G)"],
  },
  {
    name: "Espresso doppio",
    category: "Tee - Kaffee",
    code: "TEE007",
    description: "Kaffee",
    images: [],
    material: "",
    price: 4.9,
    similar: ["Espresso", "Kleiner Brauner (G)", "Melange (G)"],
  },
  {
    name: "Kleiner Brauner (G)",
    category: "Tee - Kaffee",
    code: "TEE008",
    description: "Kaffee",
    images: [],
    material: "",
    price: 3.1,
    similar: ["Espresso", "Espresso doppio", "Melange (G)"],
  },
  {
    name: "Melange (G)",
    category: "Tee - Kaffee",
    code: "TEE009",
    description: "Kaffee",
    images: [],
    material: "",
    price: 3.8,
    similar: ["Espresso", "Espresso doppio", "Kleiner Brauner (G)"],
  },
  {
    name: "Cappucino (G)",
    category: "Tee - Kaffee",
    code: "TEE010",
    description: "Kaffee",
    images: [],
    material: "",
    price: 3.8,
    similar: ["Espresso", "Espresso doppio", "Melange (G)"],
  },
  {
    name: "Latte Macchiato",
    category: "Tee - Kaffee",
    code: "TEE011",
    description: "Kaffee",
    images: [],
    material: "",
    price: 4.5,
    similar: ["Espresso", "Espresso doppio", "Melange (G)"],
  },
  {
    name: "Großer Brauner (G)",
    category: "Tee - Kaffee",
    code: "TEE012",
    description: "Kaffee",
    images: [],
    material: "",
    price: 3.8,
    similar: ["Espresso", "Espresso doppio", "Melange (G)"],
  },
  {
    name: "Verlängerter",
    category: "Tee - Kaffee",
    code: "TEE013",
    description: "Kaffee",
    images: [],
    material: "",
    price: 3.5,
    similar: ["Espresso", "Espresso doppio", "Melange (G)"],
  },
  {
    name: "Kakaotraum",
    category: "Tee - Kaffee",
    code: "TEE014",
    description: "Kaffee",
    images: [],
    material: "",
    price: 3.5,
    similar: ["Espresso", "Espresso doppio", "Kleiner Brauner (G)"],
  },
  {
    name: "Grüner Veltliner  Weinveiertel (Lobner)",
    category: "Alkoholisch",
    code: "ALK001",
    description: "Weisswein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "25,00",
      },
      {
        size: "1/81",
        price: 4.5,
      },
    ],
    similar: [
      "Riesling (Lobner)",
      "Chardonnay 2021 (Gesellmann)",
      "Oberlaa Wiener Gemishter Satz (Zahel)",
    ],
  },
  {
    name: "Riesling (Lobner)",
    category: "Alkoholisch",
    code: "ALK002",
    description: "Weisswein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "27,00",
      },
      {
        size: "1/81",
        price: 4.5,
      },
    ],
    similar: [
      "Grüner Veltliner  Weinveiertel (Lobner)",
      "Chardonnay 2021 (Gesellmann)",
      "Oberlaa Wiener Gemishter Satz (Zahel)",
    ],
  },
  {
    name: "Chardonnay 2021 (Gesellmann)",
    category: "Alkoholisch",
    code: "ALK003",
    description: "Weisswein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "35,00",
      },
      {
        size: "1/81",
        price: 6.1,
      },
    ],
    similar: [
      "Grüner Veltliner  Weinveiertel (Lobner)",
      "Riesling (Lobner)",
      "Oberlaa Wiener Gemishter Satz (Zahel)",
    ],
  },
  {
    name: "Oberlaa Wiener Gemishter Satz (Zahel)",
    category: "Alkoholisch",
    code: "ALK004",
    description: "Weisswein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "28,00",
      },
      {
        size: "1/81",
        price: "5,00",
      },
    ],
    similar: [
      "Grüner Veltliner  Weinveiertel (Lobner)",
      "Riesling (Lobner)",
      "Chardonnay 2021 (Gesellmann)",
    ],
  },
  {
    name: "Gelber Muskateller (Hagn)",
    category: "Alkoholisch",
    code: "ALK005",
    description: "Weisswein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "33,00",
      },
      {
        size: "1/81",
        price: 5.9,
      },
    ],
    similar: [
      "Grüner Veltliner  Weinveiertel (Lobner)",
      "Riesling (Lobner)",
      "Chardonnay 2021 (Gesellmann)",
    ],
  },
  {
    name: "Shiraz & Co (Salomon Estate)",
    category: "Alkoholisch",
    code: "ALK006",
    description: "Rotwein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "37,00",
      },
      {
        size: "1/81",
        price: 6.5,
      },
    ],
    similar: [
      "Shiraz Cabernet (Rosemount)",
      "Red Naked Bio / Zweigelt - Blaufränkish (G&H Heinrich)",
      "Zweigelt Rosé Bio (Brünlmayer)",
    ],
  },
  {
    name: "Shiraz Cabernet (Rosemount)",
    category: "Alkoholisch",
    code: "ALK007",
    description: "Rotwein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "29,00",
      },
      {
        size: "1/81",
        price: 5.2,
      },
    ],
    similar: [
      "Shiraz & Co (Salomon Estate)",
      "Red Naked Bio / Zweigelt - Blaufränkish (G&H Heinrich)",
      "Zweigelt Rosé Bio (Brünlmayer)",
    ],
  },
  {
    name: "Red Naked Bio / Zweigelt - Blaufränkish (G&H Heinrich)",
    category: "Alkoholisch",
    code: "ALK008",
    description: "Rotwein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "31,00",
      },
      {
        size: "1/81",
        price: 5.5,
      },
    ],
    similar: [
      "Shiraz & Co (Salomon Estate)",
      "Shiraz Cabernet (Rosemount)",
      "Zweigelt Rosé Bio (Brünlmayer)",
    ],
  },
  {
    name: "Zweigelt Rosé Bio (Brünlmayer)",
    category: "Alkoholisch",
    code: "ALK009",
    description: "Rotwein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "30,00",
      },
      {
        size: "1/81",
        price: 5.2,
      },
    ],
    similar: [
      "Shiraz & Co (Salomon Estate)",
      "Red Naked Bio / Zweigelt - Blaufränkish (G&H Heinrich)",
      "Shiraz Cabernet (Rosemount)",
    ],
  },
  {
    name: "Zb / Zweigelt - Blaufränkisch - Pinot Nior (Gesellmann)",
    category: "Alkoholisch",
    code: "ALK010",
    description: "Rotwein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "31,00",
      },
      {
        size: "1/81",
        price: 5.5,
      },
    ],
    similar: [
      "Shiraz & Co (Salomon Estate)",
      "Shiraz Cabernet (Rosemount)",
      "Red Naked Bio / Zweigelt - Blaufränkish (G&H Heinrich)",
    ],
  },
  {
    name: "Pinot Noir Bio (Leopold Auer)",
    category: "Alkoholisch",
    code: "ALK011",
    description: "Rotwein",
    images: [],
    material: "",
    price: [
      {
        size: "0,751",
        price: "37,00",
      },
      {
        size: "1/81",
        price: 6.8,
      },
    ],
    similar: [
      "Shiraz & Co (Salomon Estate)",
      "Shiraz Cabernet (Rosemount)",
      "Red Naked Bio / Zweigelt - Blaufränkish (G&H Heinrich)",
    ],
  },
  {
    name: "Bumbu Rum",
    category: "Alkoholisch",
    code: "ALK012",
    description: "Spirituosen",
    images: [],
    material: "",
    price: [
      {
        size: "70cl",
        price: "95,00",
      },
      {
        size: "2cl",
        price: 4.9,
      },
    ],
    similar: ["Absolut Vodka", "Tequilla", "Chivas"],
  },
  {
    name: "Absolut Vodka",
    category: "Alkoholisch",
    code: "ALK013",
    description: "Spirituosen",
    images: [],
    material: "",
    price: [
      {
        size: "70cl",
        price: "55,00",
      },
      {
        size: "2cl",
        price: 3.9,
      },
    ],
    similar: ["Bumbu Rum", "Tequilla", "Chivas"],
  },
  {
    name: "Tequilla",
    category: "Alkoholisch",
    code: "ALK014",
    description: "Spirituosen",
    images: [],
    material: "",
    price: [
      {
        size: "70cl",
        price: "50,00",
      },
      {
        size: "2cl",
        price: 3.5,
      },
    ],
    similar: ["Bumbu Rum", "Absolut Vodka", "Chivas"],
  },
  {
    name: "Chivas",
    category: "Alkoholisch",
    code: "ALK015",
    description: "Spirituosen",
    images: [],
    material: "",
    price: [
      {
        size: "70cl",
        price: "75,00",
      },
      {
        size: "2cl",
        price: 4.5,
      },
    ],
    similar: ["Bumbu Rum", "Absolut Vodka", "Tequilla"],
  },
  {
    name: "Jägermeister",
    category: "Alkoholisch",
    code: "ALK016",
    description: "Spirituosen",
    images: [],
    material: "",
    price: [
      {
        size: "2cl",
        price: 3.5,
      },
    ],
    similar: ["Bumbu Rum", "Absolut Vodka", "Tequilla"],
  },
  {
    name: "Schnaps (Obst / Marille / Zwetchge)",
    category: "Alkoholisch",
    code: "ALK017",
    description: "Spirituosen",
    images: [],
    material: "",
    price: [
      {
        size: "2cl",
        price: 3.1,
      },
    ],
    similar: ["Bumbu Rum", "Absolut Vodka", "Tequilla"],
  },
  {
    name: "kUBIDEH",
    category: "Mittagsmenü",
    code: "MM001",
    description:
      "Dienstag \n Faschierter Spieß aus Lamm & Rind serviert mit Safran-Reis oder Pommes",
    images: [
      "Toranj-32-Detail-Kubideh.jpg",
      "Toranj-33-Detail-Kubideh.jpg",
      "Toranj-31-Ready to Eat-Kubideh.jpg",
      "Toranj-38-Start Eating-Kubideh.jpg",
      "Toranj-39-Start Eating-Kubideh.jpg",
    ],
    material: "",
    price: 12.5,
    similar: ["Jujeh", "KUBIDEH", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "Jujeh",
    category: "Mittagsmenü",
    code: "MM002",
    description:
      "Dienstag \n Mariniertes Hügnerfilet vom Grill serviert mit Safran-Reis oder Pommes (C,G)",
    images: [],
    material: "",
    price: 13.8,
    similar: ["kUBIDEH", "KUBIDEH", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "KUBIDEH",
    category: "Mittagsmenü",
    code: "MM003",
    description:
      "Mittwoch \n Faschierter Spieß aus Lamm & Rind serviert mit Safran-Reis oder Pommes",
    images: [
      "Toranj-32-Detail-Kubideh.jpg",
      "Toranj-33-Detail-Kubideh.jpg",
      "Toranj-31-Ready to Eat-Kubideh.jpg",
      "Toranj-38-Start Eating-Kubideh.jpg",
      "Toranj-39-Start Eating-Kubideh.jpg",
    ],
    material: "",
    price: 12.5,
    similar: ["kUBIDEH", "Jujeh", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "BAGHALI POLO BA MAHICHE",
    category: "Mittagsmenü",
    code: "MM004",
    description:
      "Mittwoch \n In Kurkumabouilon gekochte Lamms serviert mit Basmati-Dillen-Reis und Dicke bohnen (G,L)",
    images: ["Toranj-14-Detail-Baghali Polo Ba Mahiche.jpg"],
    material: "",
    price: 15.5,
    similar: ["kUBIDEH", "Jujeh", "KUBIDEH"],
  },
  {
    name: "ADDAS POLO (VEG)",
    category: "Mittagsmenü",
    code: "MM005",
    description: "Mittwoch \n Reis mit gebratenen Zwiebel, Linsen und Rosinen",
    images: ["Toranj Februar 2024-36.jpg"],
    material: "",
    price: 11.9,
    similar: ["kUBIDEH", "Jujeh", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "KUBIDEH",
    category: "Mittagsmenü",
    code: "MM006",
    description:
      "Donnerstag \n Faschierter Spieß aus Lamm & Rind serviert mit Safran-Reis oder Pommes",
    images: [
      "Toranj-32-Detail-Kubideh.jpg",
      "Toranj-33-Detail-Kubideh.jpg",
      "Toranj-31-Ready to Eat-Kubideh.jpg",
      "Toranj-38-Start Eating-Kubideh.jpg",
      "Toranj-39-Start Eating-Kubideh.jpg",
    ],
    material: "",
    price: 12.5,
    similar: ["kUBIDEH", "Jujeh", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "ZERESHPOLO BA MORGH",
    category: "Mittagsmenü",
    code: "MM007",
    description:
      "Donnerstag \n Zartes Hühnerfleisch serviert mit Safran-Berberitzenreis (A,L)",
    images: [
      "Toranj-17-Food with Ingredients -Zereshk Polo Ba Morgh.jpg",
      "Toranj-15-Detail-Zereshk Polo Ba Morgh.jpg",
      "Toranj-16-One Dish-Zereshk Polo Ba Morgh.jpg",
    ],
    material: "",
    price: 12.9,
    similar: ["kUBIDEH", "Jujeh", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "CHENJEH KABAB",
    category: "Mittagsmenü",
    code: "MM008",
    description:
      "Donnerstag \n Zartes Rindfillet vom Speiß serviert mit Safran-Reis oder Pommes",
    images: [],
    material: "",
    price: 16.3,
    similar: ["kUBIDEH", "Jujeh", "BAGHALI POLO BA MAHICHE"],
  },
  {
    name: "KUBIDEH",
    category: "Mittagsmenü",
    code: "MM009",
    description:
      "Freitag \n Faschierter Spieß aus Lamm & Rind serviert mit Safran-Reis oder Pommes",
    images: [
      "Toranj-32-Detail-Kubideh.jpg",
      "Toranj-33-Detail-Kubideh.jpg",
      "Toranj-31-Ready to Eat-Kubideh.jpg",
      "Toranj-38-Start Eating-Kubideh.jpg",
      "Toranj-39-Start Eating-Kubideh.jpg",
    ],
    material: "",
    price: 12.5,
    similar: ["Jujeh", "BAGHALI POLO BA MAHICHE", "ZERESHPOLO BA MORGH"],
  },
  {
    name: "JUJEH TORSH",
    category: "Mittagsmenü",
    code: "MM010",
    description:
      "Freitag \n Fein mariniertes Huhnerfillet vom Grill, eigelegt in Granatapfelsauce & persischen Limetten (C,G)",
    images: [
      "Toranj-28-Food with Ingredients -Jujeh Torsh.jpg",
      "Toranj-29-Detail-Jujeh Torsh.jpg",
    ],
    material: "",
    price: 15.5,
    similar: ["kUBIDEH", "BAGHALI POLO BA MAHICHE", "ZERESHPOLO BA MORGH"],
  },
  {
    name: "GHORMEH SABZI",
    category: "Mittagsmenü",
    code: "MM011",
    description:
      "Freitag \n Eintopf aus erlesner, persischer Kräutermischung mit Bohnen, Rindfleisch & persischen Limetten, serviert mit Safran-Reis (L,O)",
    images: ["Toranj-19-Food with Ingredients -Ghormeh Sabzi.jpg"],
    material: "",
    price: 13.5,
    similar: ["kUBIDEH", "BAGHALI POLO BA MAHICHE", "JUJEH TORSH"],
  },
  {
    name: "DIZI",
    category: "Mittagsmenü",
    code: "MM012",
    description:
      "Samstag \n Eintopf aus Lammfleisch, Kicherebsen, Kartoffeln und Tomatten serviert mit Brot und eingelegtes Knoblauch und eigelegtes Gemüse. (Unsere Mitarbeiter erklären ihnen gerne den Essenvorgan)",
    images: ["Toranj-27-Food with Ingredients -Dizi.jpg"],
    material: "",
    price: 15.5,
    similar: ["kUBIDEH", "BAGHALI POLO BA MAHICHE", "JUJEH TORSH"],
  },
  {
    name: "TAHCHIN",
    category: "Mittagsmenü",
    code: "MM013",
    description:
      "Samstag \n Reiskuchen mit Joghurt, Ei, Safran, Huhn und Berberitzen",
    images: ["Tahchin.jpg"],
    material: "",
    price: 14.9,
    similar: ["kUBIDEH", "BAGHALI POLO BA MAHICHE", "JUJEH TORSH"],
  },
  {
    name: "Addas Polo",
    category: "Vegetarische Speisen",
    code: "VEG001",
    description:
      "Reis mit gebratenen Zwiebeln, Linsen und Rosinen serviert mit Masto Khiar (L)",
    images: ["Toranj Februar 2024-36.jpg"],
    material: "",
    price: 14.5,
    similar: [
      "Khoreshte Fesenjan (Veg)",
      "Khoreshte Bamiye (Veg)",
      "Ashe Reshte (Veg)",
    ],
  },
  {
    name: "Khoreshte Fesenjan (Veg)",
    category: "Vegetarische Speisen",
    code: "VEG002",
    description:
      "Pesischer süßlich-herber Eintopf auf der Basis von Granatapfelsirup sowie gemalenen Walnüssen und Kartoffeln, serviert mit Safran-Reis (H,O)",
    images: [
      "Toranj-6-Food with Ingredients -Khoreshte Fesenjan.jpg",
      "Toranj-7-One Dish-Khoreshte Fesenjan.jpg",
    ],
    material: "",
    price: 16.7,
    similar: ["Addas Polo", "Khoreshte Bamiye (Veg)", "Ashe Reshte (Veg)"],
  },
  {
    name: "Khoreshte Bamiye (Veg)",
    category: "Vegetarische Speisen",
    code: "VEG003",
    description:
      "Eintopf aus Okraschoten in aromatischer  Tomaten, Zwiebelsauce serviert mit Safran-Reis (O)",
    images: [
      "Toranj-10-Food with Ingredients -Khoreshte Bamiye.jpg",
      "Toranj-12-Food with Ingredients -Khoreshte Bamiye.jpg",
    ],
    material: "",
    price: 15.4,
    similar: ["Addas Polo", "Khoreshte Fesenjan (Veg)", "Ashe Reshte (Veg)"],
  },
  {
    name: "Ashe Reshte (Veg)",
    category: "Vegetarische Speisen",
    code: "VEG004",
    description:
      "Entopf mit Bulgur, Linsen, Bohnen, Minze, Koriander Petersillie serviert mit Brot (A,G,H)",
    images: [
      "Toranj-25-Food with Ingredients -Ashereshte.jpg",
      "Toranj-8-Ready to Eat-Ashereshte.jpg",
    ],
    material: "",
    price: 10.5,
    similar: [
      "Addas Polo",
      "Khoreshte Fesenjan (Veg)",
      "Khoreshte Bamiye (Veg)",
    ],
  },
  {
    name: "Toranj Salat",
    category: "Vegetarische Speisen",
    code: "VEG005",
    description:
      "Gurken, Tomaten, Radieschen, Granatapfelkern, rote, Zwiebel, firscher Minze mit Pitabrot",
    images: [],
    material: "",
    price: 8.9,
    similar: ["Khoreshte Kadu Bademjan", "Mirza Ghasemi", "Kuku Sabzi"],
  },
  {
    name: "Khoreshte Kadu Bademjan",
    category: "Vegetarische Speisen",
    code: "VEG006",
    description:
      "Gebratene und gekochte Zuccini und Auberginen, in einer leichten Tomaten-Knoblauch-Zwiebelsauce, serviert mit Safran-Reis (H,O)",
    images: [],
    material: "",
    price: 15.9,
    similar: [
      "Khoreshte Fesenjan (Veg)",
      "Khoreshte Bamiye (Veg)",
      "Ashe Reshte (Veg)",
    ],
  },
  {
    name: "Mirza Ghasemi",
    category: "Vorspeisen",
    code: "VORS001",
    description:
      "Gegrillte Auberginen und gedünstete Tomaten, verfeinert mit Knoblauch und persischen Gewürzen serviert mit Brot (C,O)",
    images: ["Toranj-11-Ready to Eat-Mirza Chasemie.jpg"],
    material: "",
    price: 6.9,
    similar: [
      "Kuku Sabzi",
      "Kashke Bademjan",
      "Vorspeisenteller for 4 Personen",
    ],
  },
  {
    name: "Kuku Sabzi",
    category: "Vorspeisen",
    code: "VORS002",
    description:
      "Persisches Omelett  aus frischen Kräutern, Ei, Mohnteigblätter, Berberitzen & geriebene Walnüssen, serviert mit Brot (A,C,G,N)",
    images: [
      "Toranj-26-Food with Ingredients -Kukusaszi.jpg",
      "Toranj-12-One Dish-Kukusaszi.jpg",
      "Toranj-14-One Dish-Kukusaszi.jpg",
    ],
    material: "",
    price: 6.5,
    similar: [
      "Mirza Ghasemi",
      "Kashke Bademjan",
      "Vorspeisenteller for 4 Personen",
    ],
  },
  {
    name: "Kashke Bademjan",
    category: "Vorspeisen",
    code: "VORS003",
    description:
      "Gehackte und gebratene Auberginen mit Kaschke*, Pfefferminz und Röstzwiebeln, verfeinert mit persischen Gewürzen und Knoblauch serviert mit Brot (A,G,H)",
    images: [
      "Toranj-7-Food with Ingredients -Kashke Bademjan.jpg",
      "Toranj-2-Ready to Eat-Kashke Bademjan.jpg",
      "Toranj-3-Ready to Eat-Kashke Bademjan.jpg",
      "Toranj-24-Food with Ingredients -Kashke Bademjan.jpg",
    ],
    material: "",
    price: 7.1,
    similar: ["Mirza Ghasemi", "Kuku Sabzi", "Vorspeisenteller for 4 Personen"],
  },
  {
    name: "Masto Khiar",
    category: "Vorspeisen",
    code: "VORS004",
    description:
      "Natur Cremejoghurt mit feingehackten Gurken, Minze serviert mit Brot (G)",
    images: ["Toranj-28-One Dish-Mastokhiar.jpg"],
    material: "",
    price: 5.5,
    similar: ["Hummus", "Kukusazbi", "Kashke Bademjan"],
  },
  {
    name: "Vorspeisenteller for 4 Personen",
    category: "Vorspeisen",
    code: "VORS005",
    description: "5 Vorspeisen nach Wahl serviert mit Brot",
    images: [
      "Toranj-24-Food with Ingredients -Vorspeisenteller.jpg",
      "Toranj-22-One Dish-Vorspeisenteller.jpg",
      "Toranj-23-Food with Ingredients -Vorspeisenteller.jpg",
    ],
    material: "",
    price: 25.8,
    similar: ["Vorspeisenteller for 2 Personen", "Hummus", "Masto Khiar"],
  },
  {
    name: "Vorspeisenteller for 2 Personen",
    category: "Vorspeisen",
    code: "VORS006",
    description: "3 Vorspeisen nach Wahl serviert mit Brot",
    images: [
      "Toranj-24-Food with Ingredients -Vorspeisenteller.jpg",
      "Toranj-22-One Dish-Vorspeisenteller.jpg",
      "Toranj-23-Food with Ingredients -Vorspeisenteller.jpg",
    ],
    material: "",
    price: 15.9,
    similar: ["Vorspeisenteller for 4 Personen", "Hummus", "Masto Khiar"],
  },
  {
    name: "Hummus",
    category: "Vorspeisen",
    code: "VORS007",
    description:
      "Kichererbsenpuree mit Tahin & Oliovenol (H,N) serviert mit Brot",
    images: ["Toranj Februar 2024-03.jpg", "Toranj Februar 2024-19.jpg"],
    material: "",
    price: 5.2,
    similar: ["Masto Khiar", "Kukusazbi", "Kashke Bademjan"],
  },
  {
    name: "Zeytoon Parvarde",
    category: "Vorspeisen",
    code: "VORS008",
    description:
      "Eingelegte persische Oliven in Spezial-Kräutergranatapfelsauce Walnüssen (H)",
    images: [
      "Toranj-27-Food with Ingredients -Zeytoon Paruarde.jpg",
      "Toranj-1-Ready to Eat-Zeytoon Paruarde.jpg",
    ],
    material: "",
    price: 6.8,
    similar: ["Hummus", "Kashke Bademjan", "Masto Khiar"],
  },
  {
    name: "Borani Esfenaj",
    category: "Vorspeisen",
    code: "VORS009",
    description: "Naut Cremojoghurt mit geräuchertem Spina und Knoblauch (G)",
    images: ["Toranj Februar 2024-09.jpg"],
    material: "",
    price: 5.6,
    similar: ["Hummus", "Zeytoon Parvarde", "Kashke Bademjan"],
  },
  {
    name: "Borani Bademjan",
    category: "Vorspeisen",
    code: "VORS010",
    description:
      "Natur Cremjoghuty mit geräuchertem Melanzani und Knoblauch (G)",
    images: [
      "Toranj Februar 2024-04.jpg",
      "Toranj Februar 2024-14.jpg",
      "Toranj Februar 2024-08.jpg",
    ],
    material: "",
    price: 5.8,
    similar: ["Hummus", "Kashke Bademjan", "Zeytoon Parvarde"],
  },
  {
    name: "Oliven",
    category: "Vorspeisen",
    code: "VORS011",
    description: "eingelegte Oliven",
    images: ["Toranj Februar 2024-07.jpg"],
    material: "",
    price: 4.5,
    similar: ["Hummus", "Zeytoon Parvarde", "Borani Bademjan"],
  },
  {
    name: "Mast Musir",
    category: "Vorspeisen",
    code: "VORS012",
    description: "Natur Cremejoghurt mit Wildknoblauch (G)",
    images: [],
    material: "",
    price: 5.4,
    similar: ["Hummus", "Zeytoon Parvarde", "Borani Bademjan"],
  },
  {
    name: "Sir Torshi",
    category: "Vorspeisen",
    code: "VORS013",
    description: "In Essig eingelegter Knoblauch",
    images: ["Toranj Februar 2024-01.jpg", "Toranj Februar 2024-20.jpg"],
    material: "",
    price: 3.9,
    similar: ["Hummus", "Zeytoon Parvarde", "Oliven"],
  },
  {
    name: "Torshi",
    category: "Vorspeisen",
    code: "VORS014",
    description: "eingelegtes Gemüse",
    images: ["Toranj Februar 2024-05.jpg"],
    material: "",
    price: 3.5,
    similar: ["Hummus", "Zeytoon Parvarde", "Oliven"],
  },
  {
    name: "Khiar Shur",
    category: "Vorspeisen",
    code: "VORS015",
    description: "Eingelegte Salzgurken nach persischer Art (L.M)",
    images: ["Toranj Februar 2024-18.jpg", "Toranj Februar 2024-17.jpg"],
    material: "",
    price: 3.6,
    similar: ["Hummus", "Zeytoon Parvarde", "Oliven"],
  },
  {
    name: "Maste Sadeh",
    category: "Vorspeisen",
    code: "VORS016",
    description: "Natur Cremjoghurt (G)",
    images: ["Toranj Februar 2024-06.jpg"],
    material: "",
    price: 3.8,
    similar: ["Hummus", "Zeytoon Parvarde", "Oliven"],
  },
  {
    name: "Ghorme Sabzi",
    category: "Eintöpfe",
    code: "EINT001",
    description:
      "Eintopf aus erlesener, persischer krautermischung mit Bohnen Rindfleisch & persischen Limetten serviert mit Safran-Reis (L,O)",
    images: ["Toranj-19-Food with Ingredients -Ghormeh Sabzi.jpg"],
    material: "",
    price: 16.3,
    similar: ["Gheyme Bademjan", "Khoreshte Fesenjan", "Khoreshte Gheyme"],
  },
  {
    name: "Gheyme Bademjan",
    category: "Eintöpfe",
    code: "EINT002",
    description:
      "Eintopf aus Melanzani, Rindfleisch, gelbe Linsen & persische Limetten in aromatischer Tomaten-Zwiebelsauce, serviert mit Safran-Reish",
    images: [
      "Toranj-8-Food with Ingredients -Gheyme Bademjan.jpg",
      "Toranj-5-One Dish-Gheyme Bademjan.jpg",
    ],
    material: "",
    price: 16.4,
    similar: ["Ghorme Sabzi", "Khoreshte Fesenjan", "Khoreshte Gheyme"],
  },
  {
    name: "Khoreshte Fesenjan",
    category: "Eintöpfe",
    code: "EINT003",
    description:
      "persischer süßlich-herber Eintopf mit Hühnerfleisch, auf der Basis von Granatapfelsirup sowie gemahlenen Walnüssen serviert mit Safran-Reis (H,O)",
    images: [
      "Toranj-6-Food with Ingredients -Khoreshte Fesenjan.jpg",
      "Toranj-7-One Dish-Khoreshte Fesenjan.jpg",
    ],
    material: "",
    price: 17.9,
    similar: ["Ghorme Sabzi", "Gheyme Bademjan", "Khoreshte Gheyme"],
  },
  {
    name: "Khoreshte Gheyme",
    category: "Eintöpfe",
    code: "EINT004",
    description:
      "Entopf aus Rindfleisch gelbe Linsen & persische Limetten in aromatischer Tomaten-Zwiebelsauce serviert mit Safran-Reis",
    images: [
      "Toranj-8-Food with Ingredients -Gheyme Bademjan.jpg",
      "Toranj-5-One Dish-Gheyme Bademjan.jpg",
    ],
    material: "",
    price: 15.9,
    similar: ["Gheyme Bademjan", "Khoreshte Fesenjan", "Ghorme Sabzi"],
  },
  {
    name: "Khoreshte Bamiye",
    category: "Eintöpfe",
    code: "EINT005",
    description:
      "Eintopf aus Rindfleisch und Okraschoten in Aromatischer Tomaten-Zwiebelsauce, serviert mit Safran-Reis (O)",
    images: [
      "Toranj-10-Food with Ingredients -Khoreshte Bamiye.jpg",
      "Toranj-12-Food with Ingredients -Khoreshte Bamiye.jpg",
    ],
    material: "",
    price: 16.2,
    similar: ["Gheyme Bademjan", "Khoreshte Fesenjan", "Ghorme Sabzi"],
  },
  {
    name: "Baghlai Polo ba Mahiche",
    category: "Grillspezialitäten",
    code: "GRILL001",
    description:
      "In Kurkumabouillon gekochte Lamms serviert  mit Basmat-Dillen-Reis",
    images: ["Toranj-14-Detail-Baghali Polo Ba Mahiche.jpg"],
    material: "",
    price: 19.5,
    similar: [
      "Baghali Polo ba Morgh",
      "Sabzi Polo ba Mahi",
      "Zereshkpolo ba Morgh",
    ],
  },
  {
    name: "Baghali Polo ba Morgh",
    category: "Grillspezialitäten",
    code: "GRILL002",
    description: "Zarte Hühnerkeule serviert mit Basmati-Dillen-Reis",
    images: [],
    material: "",
    price: 16.9,
    similar: [
      "Baghlai Polo ba Mahiche",
      "Sabzi Polo ba Mahi",
      "Zereshkpolo ba Morgh",
    ],
  },
  {
    name: "Sabzi Polo ba Mahi",
    category: "Grillspezialitäten",
    code: "GRILL003",
    description: "Lachs nach Saison serviert mit Koriander-Safranreis(A,L)",
    images: [],
    material: "",
    price: 18.1,
    similar: [
      "Baghlai Polo ba Mahiche",
      "Baghali Polo ba Morgh",
      "Zereshkpolo ba Morgh",
    ],
  },
  {
    name: "Zereshkpolo ba Morgh",
    category: "Grillspezialitäten",
    code: "GRILL004",
    description: "Zarte Hühnerkeule serviert mit Safran-Berberitzen-Reis (A,L)",
    images: [
      "Toranj-17-Food with Ingredients -Zereshk Polo Ba Morgh.jpg",
      "Toranj-15-Detail-Zereshk Polo Ba Morgh.jpg",
      "Toranj-16-One Dish-Zereshk Polo Ba Morgh.jpg",
    ],
    material: "",
    price: 16.5,
    similar: [
      "Baghlai Polo ba Mahiche",
      "Baghali Polo ba Morgh",
      "Sabzi Polo ba Mahi",
    ],
  },
  {
    name: "Kleiner gemischter Salat",
    category: "Salat & Suppen",
    code: "SALA001",
    description: "Eisbergsalat, Tomaten, Gurken und Mais",
    images: [],
    material: "",
    price: 3.7,
    similar: ["Salat Shirazi", "Toranj Salat", "Suppe Djo"],
  },
  {
    name: "Salat Shirazi",
    category: "Salat & Suppen",
    code: "SALA002",
    description:
      "Kleingeschnittene Gurken, Tomaten und Zwiebeln mit saurem Traubensaft & Olivenöl (C)",
    images: [
      "Toranj-6-Food with Ingredients -Salatshirazie.jpg",
      "Toranj-5-Detail-Salatshirazie.jpg",
      "Toranj-4-Ready to Eat-Salatshirazie.jpg",
    ],
    material: "",
    price: 4.5,
    similar: ["Kleiner gemischter Salat", "Toranj Salat", "Suppe Djo"],
  },
  {
    name: "Toranj Salat",
    category: "Salat & Suppen",
    code: "SALA003",
    description:
      "Gurken, Tomaten, Radieschen, Granatapfelkern, rote, Zwiebel, firscher Minze mit Pitabrot",
    images: [],
    material: "",
    price: 8.9,
    similar: ["Kleiner gemischter Salat", "Salat Shirazi", "Suppe Djo"],
  },
  {
    name: "Suppe Djo",
    category: "Salat & Suppen",
    code: "SALA004",
    description: "Gerstensuppe mit Hühnerbouillon serviert mit Brot (A,L)",
    images: [
      "Ingredients_Toranj_Suppe Djo.jpg",
      "Action detail_Toranj_Suppe Djo.jpg",
    ],
    material: "",
    price: 6.5,
    similar: ["Kleiner gemischter Salat", "Salat Shirazi", "Toranj Salat"],
  },
  {
    name: "Suppe Addas",
    category: "Salat & Suppen",
    code: "SALA005",
    description:
      "Linsen verfeinert mit Karoffeln und Zwiebeln serviert mit Brot (H,G)",
    images: [],
    material: "",
    price: 5.8,
    similar: ["Kleiner gemischter Salat", "Salat Shirazi", "Toranj Salat"],
  },
  {
    name: "Ashe",
    category: "Salat & Suppen",
    code: "SALA006",
    description:
      "Entopf mit Bulgur, Linsen, Bohnen, Minze, Koriander Petersillie serviert mit Brot (A,G,H)",
    images: [
      "Toranj-25-Food with Ingredients -Ashereshte.jpg",
      "Toranj-8-Ready to Eat-Ashereshte.jpg",
    ],
    material: "",
    price: 10.5,
    similar: ["Kleiner gemischter Salat", "Salat Shirazi", "Toranj Salat"],
  },
  {
    name: "Baklava",
    category: "Desserts",
    code: "DESS001",
    description:
      "In Honigsirup eingelegtes Gebäck aus Blätterteig Wallnüssen, Pistazien und Kardamon (A,C,H)",
    images: ["Toranj Februar 2024-32.jpg", "Toranj Februar 2024-33.jpg"],
    material: "",
    price: 5.8,
    similar: ["Safraneis", "Rollet", "Napeloni"],
  },
  {
    name: "Safraneis",
    category: "Desserts",
    code: "DESS002",
    description: "Eiscrem mit Safran und Schlagobers (A,C,G)",
    images: [
      "Toranj-22-One Dish-Safraneis.jpg",
      "Toranj-23-One Dish-Safraneis.jpg",
    ],
    material: "",
    price: 7.1,
    similar: ["Baklava", "Rollet", "Napeloni"],
  },
  {
    name: "Rollet",
    category: "Desserts",
    code: "DESS003",
    description:
      "Feine Bisquitrolle mit Schlagobers nach persischer Art (A,C,G,H,O)",
    images: ["Toranj Februar 2024-34.jpg"],
    material: "",
    price: 5.9,
    similar: ["Baklava", "Safraneis", "Napeloni"],
  },
  {
    name: "Napeloni",
    category: "Desserts",
    code: "DESS004",
    description: "Blätterteig mit Cremfüllung nach persicher Art (A,C,G,H)",
    images: [
      "Toranj-30-Food with Ingredients -Napeloni.jpg",
      "Toranj-31-Food with Ingredients -Napeloni.jpg",
    ],
    material: "",
    price: 6.9,
    similar: ["Baklava", "Safraneis", "Rollet"],
  },
  {
    name: "Fallodeh",
    category: "Desserts",
    code: "DESS005",
    description:
      "Traitionell persische Süẞspeise aus stärkehaltigen dünnen Nudeln und einem Sirup",
    images: [
      "Toranj-18-Action-Faloode.jpg",
      "Toranj-20-Action-Faloode.jpg",
      "Toranj-21-Action-Faloode.jpg",
    ],
    material: "",
    price: 6.9,
    similar: ["Baklava", "Safraneis", "Rollet"],
  },
  {
    name: "KINDERPORTION KUBIDEH",
    category: "Extras",
    code: "EXTR001",
    description: "1 Spiess Kubideh serviert mit Reis",
    images: [],
    material: "",
    price: 11.5,
    similar: ["KINDERPORTION JUJEH", "SAFRAN-REIS", "BAGHALI POLO REIS"],
  },
  {
    name: "KINDERPORTION JUJEH",
    category: "Extras",
    code: "EXTR002",
    description: "",
    images: [],
    material: "",
    price: 13.5,
    similar: ["KINDERPORTION KUBIDEH", "SAFRAN-REIS", "BAGHALI POLO REIS"],
  },
  {
    name: "SAFRAN-REIS",
    category: "Extras",
    code: "EXTR003",
    description: "",
    images: [],
    material: "",
    price: 4.5,
    similar: [
      "KINDERPORTION KUBIDEH",
      "KINDERPORTION JUJEH",
      "BAGHALI POLO REIS",
    ],
  },
  {
    name: "BAGHALI POLO REIS",
    category: "Extras",
    code: "EXTR004",
    description: "",
    images: [],
    material: "",
    price: 5.1,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "ZERESH POLO REIS (BERBERITZE)",
    category: "Extras",
    code: "EXTR005",
    description: "",
    images: [],
    material: "",
    price: 4.5,
    similar: [
      "KINDERPORTION KUBIDEH",
      "KINDERPORTION JUJEH",
      "BAGHALI POLO REIS",
    ],
  },
  {
    name: "SPIESS CHENJEH KABAB",
    category: "Extras",
    code: "EXTR006",
    description: "",
    images: [],
    material: "",
    price: 13.8,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "SPIESS KUBIDEH",
    category: "Extras",
    code: "EXTR007",
    description: "",
    images: [],
    material: "",
    price: 6.1,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "SPIESS JUJE",
    category: "Extras",
    code: "EXTR008",
    description: "",
    images: [],
    material: "",
    price: 11.3,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "SPIESS JUJETORSH",
    category: "Extras",
    code: "EXTR009",
    description: "",
    images: [],
    material: "",
    price: 12.5,
    similar: [
      "KINDERPORTION KUBIDEH",
      "KINDERPORTION JUJEH",
      "BAGHALI POLO REIS",
    ],
  },
  {
    name: "GEGRILLTE TOMATEN",
    category: "Extras",
    code: "EXTR010",
    description: "3 Stück \n 3 pieces",
    images: [],
    material: "",
    price: 3,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "SPIESS BARG",
    category: "Extras",
    code: "EXTR011",
    description: "",
    images: [],
    material: "",
    price: 14.8,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "BROTKORB نان",
    category: "Extras",
    code: "EXTR012",
    description: "",
    images: [],
    material: "",
    price: 2.1,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "TORTENSERVICE",
    category: "Extras",
    code: "EXTR013",
    description: "für selbst mitgebrachte Toren - pro Person",
    images: [],
    material: "",
    price: 1.9,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "TRAGETASCHE",
    category: "Extras",
    code: "EXTR014",
    description: "",
    images: [],
    material: "",
    price: 0.3,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
  {
    name: "EINWEGGESCHIRR",
    category: "Extras",
    code: "EXTR015",
    description: "",
    images: [],
    material: "",
    price: 0.5,
    similar: ["KINDERPORTION KUBIDEH", "KINDERPORTION JUJEH", "SAFRAN-REIS"],
  },
];
